### ISSUE TITLE
Bad Z3 encoding from partially-applied recursive function in pattern

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1575]
This code causes Z3 to raise an error, seemingly from the `existsL p` pattern.

```fstar
let rec existsL (p l : int) = True

let lem p : Lemma True [SMTPat (existsL p)] = ()

(* This is just to trigger a query *)
assume val phi : prop
assume Phi : phi
let _ = assert phi
```
(edited to reduce polymorphism)

```
Bug.fst(13,0-13,18): (Error 276) Unexpected output from Z3: (error "line 92471 column 67: Wrong number of arguments (1) passed to function (declare-fun Bug.existsL.fuel_instrumented (Fuel Term Term Term) Term)")

Verified module: Bug (341 milliseconds)
1 error was reported (see above)
```

**Comment by mtzguido** [comment]
Seems to have been fixed.

**Comment by aseemr** [comment]
The issue still exists, for example, the following modified version (where the postcondition of `lem` is non-trivial) fails with the same error:

```
let rec existsL (p l : int) = True

assume val q : prop

let lem p : Lemma q [SMTPat (existsL p)] = admit ()

(* This is just to trigger a query *)
assume val phi : prop
assume Phi : phi
let _ = assert phi
```

**Comment by aseemr** [comment]
Another example from @VincentCheval:

```
module Sem.Term2

(****** Interface *******)

type funsymbol = int

type variable =
  {
    v_name: string
  }

type name = int

type term =
  | Var : v:variable -> term
  | Name : n:name -> term
  | Func : s:funsymbol -> l:list term -> term

(** Occurrence function **)

val occurs: variable -> term -> bool
val occurs_list: variable -> list term -> bool
let rec occurs x t= match t with
  | Var v -> v = x
  | Name _ -> false
  | Func _ args -> occurs_list x args
and occurs_list x l = match l with
  | [] -> false
  | t::q -> occurs x t || occurs_list x q

assume val spec_occurs_list_exists: x:variable -> l:list term -> Lemma
  (ensures (occurs_list x l <==> FStar.List.Tot.existsb (occurs x) l))
  [SMTPat (occurs_list x l)]

assume val get_vars_list: l:list term -> list variable -> list variable

val spec_get_vars_list: l:list term -> acc:list variable -> Lemma
  (forall (x:variable). (FStar.List.Tot.mem x (get_vars_list l acc) <==> (FStar.List.Tot.mem x acc \/ occurs_list x l)))
```

If we eta-expand the partially applied occurrence of `occur` in `spec_occurs_list_exists` to `fun t -> occurs x t`, then it works.

In this example, if we add `type variable = int` then it works. Because, it looks like, with that `spec_gar_vars_list` does not require an smt query. As soon as we add `let _ = assert (hasEq nat)` after that, we get the same error.
