### ISSUE TITLE
SMT Encoding Issue (?)

### ISSUE THREAD

**Issue by kkohbrok** [FStarLang/FStar#1820]
The following fails for me with the output:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
FStar_SMTEncoding_Env.Inner_let_rec
```
Unfortunately, I was not able to make it much smaller. Setoids here is in `examples/rel/
```
module Test

open FStar.Bytes
open Setoids

let tape = nat -> Tot byte
let index = nat

let default_tape_rel = lo tape
let default_index_rel = lo index

let triple_rel (#a:Type) (#b:Type) (#c:Type) (arel:rel a) (brel:rel b) (crel:rel c) (p0 p1:(a & b & c)) : prop =
  let (x0, y0, z0) = p0 in
  let (x1, y1, z1) = p1 in
  x0 `arel` x1 /\
  y0 `brel` y1 /\
  z0 `crel` z1

let eff' (#s:Type) (#a:Type) (srel:rel s) (arel:rel a) (trel:rel tape) (irel:rel index) =
  (trel ** srel) ^--> (triple_rel arel srel irel)

#set-options "--z3rlimit 50 --max_fuel 1 --max_ifuel 2"
let sample_multiple #s #srel (length:nat) : eff' srel (lo (lbytes length)) default_tape_rel default_index_rel =
  fun (t, s) ->
  let rec sample_inner c =
    match c with
    | 0 -> empty_bytes
    | c' ->
      let b = t (c - 1) in
      let rest = sample_inner (c - 1) in
      append rest (create 1ul b)
  in
  let b_string = sample_inner length in
  b_string, s, length
```
@nikswamy you are probably the most familiar with the context. Any idea what the problem is here?

**Comment by aseemr** [comment]
@kkohbrok, can you please try with F* master (or after merging F* master in). I fixed a similar issue recently. (Also in which branch do I access the `Setoid` module?) In any case, F* master might also just say that `sample_inner` and its enclosing top-level let binding is not encoded precisely to the solver. So, you may just hoist `sample_inner` out.

But please let me know if the exception is still there in F* master.

**Comment by kkohbrok** [comment]
Right, I'll try that. Compiling as we speak. Sorry, I forgot to mention the branch. It's in `nik_lib`.

I'll try hoisting out `sample_inner` for the time being. Thanks for the tip!

**Comment by kkohbrok** [comment]
Seems like you were on the right track. It still doesn't work, but now the error message is
```
(Error) Could not encode the query since F* does not support precise smtencoding of inner let-recs yet (in this case sample_inner)
```
So it still doesn't work, but at least it's clear why :-)

OT: Much improved error messages in general now. Nice!
