### ISSUE TITLE
Requires clause not assumed when checking well-formedness of ensures clause

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#57]
The following type-checks

```
val well_typed : o:(option nat){is_Some o} -> u:unit{Some.v o = 42}
```

But the same thing written with `requires` and `ensures` doesn't:

```
val ill_typed : o:(option nat) -> Lemma
      (requires (is_Some o))
      (ensures (Some.v o = 42))
```

The error:

```
Error bug57.fst(5,0-8,0): The following problems were found:
    Subtyping check failed; expected type _119:(option ){(b2t (is_Some _119))}; got type (option nat) (bug57.fst(7,23-7,24))
```

It seems that we don't assume the `requires` clause is true when checking the well-formedness of the `ensures` clause.

**Comment by nikswamy** [comment]
Changing this to an enhancement ... it's really not designed to behave this way at the moment.

**Comment by catalin-hritcu** [comment]
This confuses beginners big time, as we saw at the Nancy summer school. Wondering whether a usability improvement for this is still on the radar.

**Comment by mtzguido** [comment]
We might be able to hack this, right?

Consider (note the type for `post`, which assumes `pre`):
```
effect Pure_wf (a:Type) (pre:pure_pre) (post:squash pre -> pure_post a) =
        PURE a
             (fun (p:pure_post a) -> pre /\ (forall (x:a). post () x ==> p x))
```
Then this succeeds.
```
val well_typed : o:(option nat) -> Pure_wf unit (Some? o) (fun _ () -> Some?.v o == 42)
let well_typed o = admit ()
```

Maybe we can define `Lemma` in terms of `Pure_wf`, and get the assumption of the precondition too. There's some work to be done in updating our code base and maybe changing desugaring to add the extra thunking.

WDYT?

**Comment by mtzguido** [comment]
Actually one can even put the `pre` precondition on the argument for `post`, and leave `Pure` unchanged externally while allowing to assume the precondition. `Lemma` does need a resugaring change, but seems easy enough.

**Comment by mtzguido** [comment]
A tentative fix in the `guido_57` branch. Only a tiny regressions related to coercing `b:bool{phi}` to `Type` (the refinement was preventing). A test in `examples/micro-benchmarks/AssumeRequires.fst`.

I'm tempted to add the needed resugaring to `Lemma` and get this to master.

**Comment by nikswamy** [comment]
This is very slick! : ) Great job killing one of our oldest issues!

Would be great to try to get this into master. And ideally use a similar trick for all our commonly used abbreviations Lemma, Pure, Ghost, ST, etc.

**Comment by nikswamy** [comment]
I expect we'll get some push back from folks about the additional `_` here:
```
val well_typed : o:(option nat) -> Pure unit (Some? o) (fun _ -> Some?.v o == 42)  
```

Could we maybe add a little desugaring support to make this a bit lighter and backwards compatible? For instance, can we desugar `(ensures e)` to `(fun _ -> e)`?

**Comment by mtzguido** [comment]
That's not an extra one, it's the result! There is no extra anything for Pure, but we need something like what you describe for Lemma (since there's no argument where we can piggyback the `pre`).

**Comment by nikswamy** [comment]
oh right ... yeah, silly me.

**Comment by mtzguido** [comment]
I added this dependency for all effects I could find in our library, and for `Lemma` with custom resugaring as well. I passed all regressions locally, but CI blew up and took over one hour to fail. Maybe it's because I regenerated hints (AFAICS: te

**Comment by mtzguido** [comment]
Documenting the trick here, just in case my branch gets too stale.

For pure, this is just what we said previously. The nicest way I could find to make the change is:
```
let pure_post' (a:Type) (pre:Type) = (_:a{pre}) -> GTot Type0
let pure_post  (a:Type) = pure_post' a True
[...]
effect Pure (a:Type) (pre:pure_pre) (post:pure_post' a pre) =
        PURE a
             (fun (p:pure_post a) -> pre /\ (forall (x:a). post x ==> p x))
```
Then `pure_post` retains the previous semantics, which is: a total, uncondionally-well-defined postcondition. This goes exactly the same for `Ghost`, `Div`, and `Exn`.

For `St`, the shape is the following:
```
let st_post_h' (heap:Type) (a:Type) (pre:Type) = a -> _:heap{pre} -> GTot Type0
let st_post_h  (heap:Type) (a:Type) = st_post_h' heap a True
[.. some indirections in between ..]
effect ST (a:Type) (pre:st_pre) (post: (h:heap -> Tot (st_post' a (pre h)))) =
  STATE a (fun (p:st_post a) (h:heap) -> pre h /\ (forall a h1. post h a h1 ==> p a h1))
```
So the WF for `post` depends on `pre h0`, with `h0` the initial heap.

Then all of these work
```
module AssumeRequires

(* NB: we need the underscore in the postcondition, instead of just (), due to #1295 *)
val well_typed : o:(option nat) -> Pure unit (Some? o) (fun _ -> Some?.v o == 42)
let well_typed o = admit ()

val get : o:(option 'a) -> Pure 'a (Some? o) (fun x -> Some?.v o == x)
let get (Some x) = x

val get_div : o:(option 'a) -> Div 'a (Some? o) (fun x -> Some?.v o == x)
let get_div (Some x) = x

// Lemma works too
val lem : o:(option unit) -> Lemma (requires (Some? o)) (ensures (Some?.v o == ()))
let lem o = ()

// Testing misc effects
val get_ghost : o:(option 'a) -> Ghost 'a (Some? o) (fun x -> Some?.v o == x)
let get_ghost (Some x) = x

val get_exn : o:(option 'a) -> Exn 'a (Some? o) (fun x -> V (Some?.v o) == x)
let get_exn (Some x) = x

open FStar.ST

val get_st : o:(option 'a) -> ST 'a (fun h0 -> Some? o) (fun h0 x h1 -> Some?.v o == x)
let get_st (Some x) = x

open FStar.HyperHeap.All

val get_all : o:(option 'a) -> All 'a (fun h0 -> Some? o) (fun h0 x h1 -> V (Some?.v o) == x)
let get_all (Some x) = x
```

**Comment by aseemr** [comment]
Very cool, @mtzguido!

**Comment by mtzguido** [comment]
Now in master :)

Note that a logical next step is asking whether the *return type*'s well-formedness can depend on the precondition, as in
```
val fails : o:(option 'a) -> Pure (x:'a{x == Some?.v o}) (requires (Some? o))
                                                         (ensures (fun _ -> True))
let fails (Some x) = x
```
but I really don't see a way of making that work.

**Comment by aseemr** [comment]
Noting a case of using this fix with `Classical.move_requires` that does not work well. Consider the following example:

```
assume val req (r:int) :Type0
assume val ens (r:int{req r}) :Type0

assume val foo (r:int) :Lemma (requires (req r)) (ensures (req r /\ ens r))

let baz () :unit =
  let _ = Classical.move_requires foo in
  ()
```

The example goes through. But note the duplication of `req r` in the `ensures` clause. With this fix, I tried:

```
assume val req (r:int) :Type0
assume val ens (r:int{req r}) :Type0

assume val foo (r:int) :Lemma (requires (req r)) (ensures (ens r))

let baz () :unit =
  let _ = Classical.move_requires foo in
  ()
```

This doesn't work. Basically, the type of `move_requires` is:

```
let move_requires (#a:Type) (#p:a -> Type) (#q:a -> Type)
($f:x:a -> Lemma (requires (p x)) (ensures (q x))) (x:a)
: Lemma (p x ==> q x) = ...
```

When called in the code above, F* solves the implicit `q` to `fun (r:int) -> ens r`. And when this solution is typechecked, it raises an error, since `ens r` requires `req r`.

I tried changing the type of `move_requires` to:

```
let move_requires (#a:Type) (#p:a -> Type) (#q:(x:a{p x}) -> Type)
($f:x:a -> Lemma (requires (p x)) (ensures (q x))) (x:a)
: Lemma (p x ==> q x) = ...
```

Note the refinement on the argument of `q`. But this still does not work. The reason is: F*, as before, solves `q` to `fun (r:int) -> ens r`, and then tries to typecheck the solution at type `fun (r:int{req r}) -> Type0`. Since the argument `r` is annotated in both cases, it tries to prove that the two argument types are equal, i.e. `True <==> req r`, which it fails to prove.

In such cases, it is still better to annotate `req r` as a refinement of `r`:

```
assume val foo (r:int{req r}) :Lemma (requires True) (ensures (ens r))
```

**Comment by catalin-hritcu** [comment]
@mtzguido Should we reopen this one? :)

**Comment by aseemr** [comment]
I think it's an issue with move_requires, I just wrote it here for record. This bug can remain closed :).

**Comment by mtzguido** [comment]
Yes, I think it's a separate thing. The first failure is because the logical assumptions are not used when typechecking the implicit (known and maybe tracked elsewhere?). And the second fix @aseemr attempted fails since unification doesn't add the refinement of `r`, if I understand correctly. This variant works, but one needs to annotate the postcondition on most (all?) uses of `move_requires`:
```
index 69345c0dc..68f6725ac 100644
--- a/ulib/FStar.Classical.fst
+++ b/ulib/FStar.Classical.fst
@@ -98,7 +98,7 @@ let exists_elim goal #a #p have f =
   let open FStar.Squash in
   bind_squash #_ #goal (join_squash have) (fun (| x, pf |) -> return_squash pf; f x)
 
-let move_requires (#a:Type) (#p:a -> Type) (#q:a -> Type)
+let move_requires (#a:Type) (#p:a -> Type) (#q:(x:a{p x}) -> Type)
   ($f:x:a -> Lemma (requires (p x)) (ensures (q x))) (x:a)
   : Lemma (p x ==> q x) =
       give_proof
@@ -113,12 +113,12 @@ let move_requires (#a:Type) (#p:a -> Type) (#q:a -> Type)
 val forall_impl_intro :
   #a:Type ->
   #p:(a -> GTot Type) ->
-  #q:(a -> GTot Type) ->
+  #q:((x:a{p x}) -> GTot Type) ->
   $f:(x:a -> (squash(p x)) -> Lemma (q x)) ->
   Lemma (forall x. p x ==> q x)
 let forall_impl_intro #a #p #q $f =
   let f' (x:a) : Lemma (requires (p x)) (ensures (q x)) = f x (get_proof (p x)) in
-  forall_intro (move_requires f')
+  forall_intro (move_requires #_ #_ #q f')
 
 // Thanks KM, CH and SZ
 val impl_intro_gen
@@ -133,7 +133,7 @@ let impl_intro_gen #p #q f =
   =
    give_proof #(q ()) (f (get_proof p))
   in
-  move_requires g ()
+  move_requires #_ #_ #(fun _ -> p ==> q ()) g ()
 
 val ghost_lemma: #a:Type -> #p:(a -> GTot Type0) -> #q:(a -> unit -> GTot Type0) ->
   $f:(x:a -> Ghost unit (p x) (q x)) -> Lemma (forall (x:a). p x ==> q x ())
```
```
$ cat A.fst 
module A

assume val req (r:int) :Type0
assume val ens (r:int{req r}) :Type0

assume val foo (r:int) :Lemma (requires (req r)) (ensures (ens r))

let baz () :unit =
  let _ = Classical.move_requires #_ #_ #ens foo in
  ()
```

**Comment by catalin-hritcu** [comment]
Please file a separate issue for this then.

**Comment by ad-l** [comment]
Anyone has a solution to use the post-condition of a function to typecheck its return type? We would really like to use this pattern in stateful functions but it seems hard to do in the current ST effect.

**Comment by mtzguido** [comment]
I think that's just impossible to do now. Given how our effects are defined, we need the return type before anything else.

**Comment by s-zanella** [comment]
Documenting that the fix for this issue breaks explicit type annotations in the result type in `ensures` clauses (this happened in mitls recently: https://github.com/mitls/mitls-fstar/commit/b58aac2f9aa36e2746ff937b405cea32893a2ee9).

```
assume type t
assume val p : Type0

(** Works *)
val f: unit -> Pure t
  (requires p)
  (ensures (fun (y:t{p}) -> True))

(** Fails with `Type annotation parameter incompatible with the expected type` *)
val g: unit -> Pure t
  (requires p)
  (ensures (fun (y:t) -> True))
```

**Comment by catalin-hritcu** [comment]
Ouch, shouldn't subtyping have taken care of this one?

**Comment by catalin-hritcu** [comment]
Reopening until Santiago's remark is properly discussed.

**Comment by aseemr** [comment]
This could be related to one of the remarks I made above: when the lambda argument is annotated, as well as there is an expected arrow type, the typechecker enforces that the argument types of the two are same. There is a comment in `TcTerm.fs` related to this.

**Comment by mtzguido** [comment]
The error stems from `check_binders`, where the binders between the abstraction and the context are compared by equality and not subtyping. Changing to subtyping makes Santiago's example succeed, but not Aseem's, and further breaks makes many things crash (prims included). I'll investigate a bit more to see what's going on.

**Comment by s-zanella** [comment]
The problem is the explicit type annotation in `Prims.pure_post'`:
```F#
let pure_post' (a:Type) (pre:Type) = _:a{pre} -> GTot Type0

effect Pure (a:Type) (pre:pure_pre) (post:pure_post' a pre) =
        PURE a (fun (p:pure_post a) -> pre /\ (forall (x:a). post x ==> p x))
```
Subtyping should have helped here, why didn't it?

**Comment by mtzguido** [comment]
We're simply not calling subtyping, but type equality; needlessly, it seems, but I need to look better to be sure.

Sorry about the breakage, by the way, it's surprising regressions didn't catch this at all.

**Comment by s-zanella** [comment]
Thanks @mtzguido. If we have to make a trade off, I think the current behaviour (after the fix) is not too problematic for `requires`/`ensures`.

Comparing the type of binders for equality makes subtyping for functions weird anyway
```F#
assume type a
assume val p : Type0
assume val q : Type0
assume val u : u:unit{q}

let f : unit -> u:unit{q} = fun (u:unit) -> u
let g : u:unit{p} -> unit = f // Works
let h : u:unit{p} -> unit = fun (u:unit) -> u // fails
```

**Comment by nikswamy** [comment]
I'm working in this code while also trying to solve #1341 

I will try to weaken the check_binders equality test to use subtyping also.

**Comment by nikswamy** [comment]
ha.

```
`fstar_and_friends uregressions` on bf182712 (nik_57) is a *failure :crying_cat_face:*
      *Project:* FStar
      *Message:* snap
      *Author:* Nikhil Swamy
      *Duration:* 16m47s
      *OS:* CYGWIN_NT-10.0
      *Logs:* stderr stdout+stderr
      *A total of 388 hints failed to replay* (not replayable, worst offenders)
      *There were errors :rage: in:* AllocST.fst AllocSTwHeaps.fst Ariadne.fst Arith.fst ArrayRealized.fst ArrayUtils.fst Asm1.fst Benton2004.fst Bijection.fst BinarySearchTree.fst BinarySearchTree0.fst BinarySearchTreeBasic.fst BinarySearchTreeFirst.fst BinaryTrees.fst BinaryTreesEnumeration.fst bug022.fst bug126.fst bug173.fst bug175.fst bug184.fst bug184Eta.fst bug213.fst bug237b.fst bug238.fst bug260.fst bug264.fst bug279.fst bug281.fst bug316.fst bug397.fst bug433.fst bug574.fst bug577.fst bug579.fst bug601.fst bug686.fst bug769c.fst bug844.fst BugWildcardTelescopes.fst CntFormat.fst CntProtocol.fst CPS.DoubleDefun.fst CPS.Expr.fst CPS.SimpleDefun.fst Effects.Def.fst EnumParsing.fst EtM.AE.fst EtM.CPA.fst Eval.DB.fst Ex04e.fst Ex07a.fst Ex07b.fst Ex07c.fst Ex07d.fst Ex10a.fst Ex12b.RPC.fst Ex12b1.Format.fst Ex12b2.Format.fst Ex12c.Format.fst Ex12f.TMAC.fst Ex12g.TMAC2.fst Formatting.fst FStar.DM4F.Heap.fst FStar.DM4F.Heap.Random.fst GC.fst Gcd.fst Huffman.fst IfcComposeReify.fst IfcDeclassify.fst IfcDelimitedRelease.fst IfcDelimitedReleaseReify.fst IfcExampleReify3.fst IfcRecursiveReify.fst IfcRules.fst IfcRulesReify.fst ImmutableST.fst ImmutableSTwHeaps.fst IntegerParsing.fst KeyValue.fst LambdaOmega.fst Lens.fst MAC.fst MerkleTree.fst MonotonicArray.fst MRefHeap.fst NatHeap.fst NetKat.fst NormVsSMT.fst ParSubst.fst Platform.Bytes.fst Point.fst Positivity.fst Print.Test.fst Printers.fst Problem01.fst ProgramEquivalence.fst ProgramOptimizations.fst propImpredicativeAndNonStrictlyPositiveinductives.fst PropositionalExtensionalityInconsistent.fst Protocol.fst QuickSort.Seq.fst RBTree.fst Rel.fst Serializing.fst SfBasic.fst SfLists.fst SfPoly.fst Sig.fst SimplePrintf.fst Simplifier.fst Slice.fst StackMachine.fst StatefulLens.fst StlcCbvDbParSubst.fst StlcCbvDbPntSubstNoLists.fst StlcStrongDbParSubst.fst StreamAE.fst Swap.fst termination.fst Trace.fst Unification.fst UnificationCrash.fst UnionFind.Forest.fst UnionFind.fst UnionFind.Functions.fst Unit1.Basic.fst Unit1.Projectors1.fst Unit1.RecursiveTypeFunctions.fst Unit2.fst UnitTests.fst UserTactics.fst Vector.fst VectorParsing.fst WhileReify.fst X64.Machine_s.fst X64.Poly1305.Math_i.fst X64.Poly1305.Spec_s.fst X64.Semantics_s.fst X64.Vale.Lemmas_i.fst X64.Vale.StrongPost_i.fst
      *VSTS Build definition:* FStar-CI-Windows```

**Comment by nikswamy** [comment]
fixed since fab0d820c8e342f16e83c5e1b4734876e5a59106

@aseemr @mtzguido @s-zanella : does it help in your use cases?

**Comment by mtzguido** [comment]
Yes! Both seem to work.

But note that if we annotate `ensures (fun (x:t) -> ...` then the precondition will **not** be assumed in the function body, since we're declaring a "weaker" type for the argument. Kind of related to #1295, but maybe not much we can do about it.

Closing yet again :) ...

**Comment by aseemr** [comment]
It still does not work for my example with `move_requires` above, but I think that's a fix in the unifier, and there is a separate issue for that already (#1338).

**Comment by aseemr** [comment]
Thanks for the fix though! It should help fixing the surprising behaviors like those pointed out by Santiago above.

**Comment by aseemr** [comment]
Haven't debugged yet why, but I had to repeat the requires clause for `ST` here: https://github.com/FStarLang/FStar/commit/a99ae0fdb5c9789e0dc38d43cb29c96e310c1c89#diff-3f1d66d050438f4c5e1acbefb0bb75adR234.

**Comment by mtzguido** [comment]
I made a typo in `FStar.HyperStack.ST`, fixing soon..

**Comment by aseemr** [comment]
Cool, thanks! Please feel free to use the branch `aseem_extend_monotonic_map` if you want to test it on the code above.
