### ISSUE TITLE
`abstract` not honored for record field accesses

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/FStar#777]
```
module A
abstract type u = { fd : unit }

module B
open A
let f   = { fd = () }   (* <-- should fail *)
let g x = x.fd          (* <-- should fail *)
```

Accessing a field of an abstract record type should not be allowed. It currently is.

**Comment by tahina-pro** [comment]
Build failed because examples/low-level/crypto/Crypto.Symmetric.Plain.fst is using the `idx` field of the abstract record type `buffer`.

**Comment by s-zanella** [comment]
6e620e4 removes the use of the `idx` field in `Crypto.Plain.fst`. The build should work now.

**Comment by tahina-pro** [comment]
I created branch `taramana_777_c_record_aead` to merge `taramana_777` and the rest of `master` into `c_record_aead`, and there, build still fails, this time because of the `a` field of type `accBuffer` in `Crypto.Symmetric.UF1CMA`, which was declared abstract. More precisely, using the following command:

```
make -C examples/low-level/crypto Crypto.AEAD.Encoding.fst-ver OTHERFLAGS='--lax --prn'
```

I obtain the following error message:

```
./Crypto.AEAD.Encoding.fst(207,42-207,43) : (Error) Expected expression of type "FStar.HyperStack.some_ref"; got expression "a#11219" of type "(Crypto.Symmetric.UF1CMA.accBuffer i#11217)"
```

Please use branch `taramana_777_c_record_aead` to solve this and the later abstraction issues that will arise from `c_record_aead`. Solving all of them is a prerequisite for the fix to #777 to be merged back to `master`.

**Comment by s-zanella** [comment]
Should be `fixed` by https://github.com/FStarLang/FStar/commit/c23f2f91b2f9afee4f2bce54d73d97b999bc184f

Waiting for CI to confirm...

**Comment by s-zanella** [comment]
Merged `taramana_777_c_record_aead` into `master` and `master` into `c_record_aead`.
I'm deleting `taramana_777_c_record_aead`
