### ISSUE TITLE
Using FStar interface

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#98]
Hello,

I was wondering if it was in your plan to allow the possibility of having interfaces for modules. I found that feature very important when dealing with big proofs that needs to be divided into lot of small proofs. It becomes quite difficult to navigate between modules without a proper interface.

Thanks a lot

Vincent

**Comment by catalin-hritcu** [comment]
@aseemr: Caching should be working now, right? Could you explain how does one use that feature in practice?

**Comment by aseemr** [comment]
Catalin: it's not fully up and running yet. I am still getting errors in some of the regression tests.

**Comment by catalin-hritcu** [comment]
We have other features now that give us similar behavior:
- [hints](https://github.com/FStarLang/FStar/wiki/Hints-%28or-how-to-replay-verification-in-milliseconds-instead-of-minutes%29)
- `--verify_module` (which is actually quite often the default) only lax-checks dependencies
